name: pytest

on:
  push:
    branches:
      - main
      - develop
  pull_request:


jobs:
  pytest:
    uses: pnx-si/geonature/.github/workflows/gn-module-pytest.yml@develop
    with:
      geonature_repo: naturalsolutions/geonature
      geonature_ref: fredon
