name: pytest

on:
  push:
    branches:
      - main
      - develop
  pull_request:


jobs:
  pytest:
    uses: bouttier/geonature/.github/workflows/gn-module-pytest.yml@feat/workflow-geonature-repo
    with:
      geonature_repo: bouttier/geonature
      geonature_ref: bump-geo
